"""FDL-first helpers for source-backed gem5 raw stat audits."""

from .audit import (
    COUNTER_BINDING_COLUMNS,
    COUNTER_OBSERVATION_COLUMNS,
    Gem5AuditResult,
    LoadedGem5Model,
    audit_raw_stat_long,
    audit_raw_stat_long_path,
    audit_gem5_stats,
    bind_counter_values,
    build_counter_binding_table,
    build_counter_observations,
    counter_gem5_stats,
    gem5_stat_coverage,
    load_fdl_model,
    require_fully_bound_model,
    unbound_model_counters,
)
from .countpointer import (
    CountRelationArtifact,
    CountPointerArtifacts,
    QAtomArtifact,
    build_count_relations,
    build_countpointer_artifacts,
    build_q_atoms,
)
from .raw_stats import (
    WINDOW_KEY_COLUMNS,
    iter_window_stats,
    numeric_gem5_value,
    read_raw_stat_long,
    validate_raw_stat_long,
)
from .sidecar import (
    CounterBinding,
    Gem5Sidecar,
    SourceReference,
    load_sidecar,
)
from .source_index import SourceEvidence, validate_source_references

__all__ = [
    "COUNTER_BINDING_COLUMNS",
    "COUNTER_OBSERVATION_COLUMNS",
    "CounterBinding",
    "CountPointerArtifacts",
    "CountRelationArtifact",
    "Gem5AuditResult",
    "Gem5Sidecar",
    "LoadedGem5Model",
    "QAtomArtifact",
    "SourceEvidence",
    "SourceReference",
    "WINDOW_KEY_COLUMNS",
    "audit_raw_stat_long",
    "audit_raw_stat_long_path",
    "audit_gem5_stats",
    "bind_counter_values",
    "build_counter_binding_table",
    "build_counter_observations",
    "build_count_relations",
    "build_countpointer_artifacts",
    "build_q_atoms",
    "counter_gem5_stats",
    "gem5_stat_coverage",
    "iter_window_stats",
    "load_fdl_model",
    "load_sidecar",
    "numeric_gem5_value",
    "read_raw_stat_long",
    "require_fully_bound_model",
    "unbound_model_counters",
    "validate_raw_stat_long",
    "validate_source_references",
]
